"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

const customerName=(i:any)=>i.customer?.display_name||i.customer?.company_name||i.customer?.email||i.auth_user_id||"Customer";
export default function OrbitFSUpdateReleaseDeployer(){
 const sb=useMemo(()=>createClient(),[]),[data,setData]=useState<any>(),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function headers(){const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(){setBusy("load");const r=await fetch("/api/admin/orbitfs",{headers:await headers(),cache:"no-store"}),j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return setMsg(j.error||"Could not load release deployment data.");setData(j);setMsg("")}
 useEffect(()=>{void load()},[]);
 async function update(installationId:string,version?:string){const target=version||data?.latestUpdate?.version;if(!target)return setMsg("No published update release is available.");if(!confirm(`Deploy OrbitFS update ${target} to this installation?`))return;setBusy(installationId);const r=await fetch("/api/admin/orbitfs/deploy",{method:"POST",headers:{...(await headers()),"content-type":"application/json"},body:JSON.stringify({installationId,action:"update",version:target})}),j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?`Update ${target} started.`:j.error||"Update failed.");if(r.ok)await load()}
 const updates=(data?.releases||[]).filter((r:any)=>r.channel==="update").sort((a:any,b:any)=>String(b.updatedAt).localeCompare(String(a.updatedAt))),latest=data?.latestUpdate,installs=(data?.installations||[]).filter((i:any)=>i.release_version);
 return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">MY ORBITFS · UPDATE & RELEASE DEPLOYER</div><h1>Update Release Deployer</h1><p>Publish eligibility stays in License Master. This screen controls when a published Base update is actually deployed to customer installations.</p></div><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div>
 <section className="lmCard"><header><div><div className="lmKicker">LATEST PUBLISHED UPDATE</div><h2>{latest?.version||"No update available"}</h2><p>{latest?.title||"Create and publish an update from the release workflow."}</p></div>{latest&&<span>{latest.severity||"normal"}</span>}</header><div className="lmKV"><div><span>Release ID</span><b>{latest?.releaseId||"—"}</b></div><div><span>Minimum version</span><b>{latest?.minimumVersion||"—"}</b></div><div><span>Required</span><b>{latest?.required?"Yes":"No"}</b></div><div><span>Rollout</span><b>{latest?.rollout||"—"}</b></div></div>{latest?.changelog&&<div className="lmNotice" style={{marginTop:14}}><b>Changelog</b><p style={{whiteSpace:"pre-wrap"}}>{latest.changelog}</p></div>}</section>
 <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">DEPLOY</div><h2>Customer updates</h2><p>Choose the installation and explicitly deploy the published update. The customer database and existing Vercel project are retained.</p></div></header>{installs.length?<div className="lmReleaseList">{installs.map((i:any)=>{const newer=latest&&i.release_version!==latest.version;return <div className="lmRelease" key={i.id}><div><b>{customerName(i)}</b><small>{i.installation_id||i.id} · installed {i.release_version}</small><p>{i.vercel_project_name||"Vercel project"} · {i.health_status||"health unknown"}</p></div><span>{newer?"UPDATE AVAILABLE":"CURRENT"}</span><div className="actions"><button className="primary" disabled={!!busy||!newer} onClick={()=>void update(i.id)}>{busy===i.id?"Updating…":newer?`Deploy ${latest.version}`:"Current"}</button></div></div>})}</div>:<div className="lmEmpty">No deployed OrbitFS installations are currently available for update.</div>}{msg&&<p className="small" style={{marginTop:12}}>{msg}</p>}</section>
 <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">RELEASE HISTORY</div><h2>Published updates</h2></div></header><div className="lmReleaseList">{updates.map((r:any)=><div className="lmRelease" key={r.releaseId}><div><b>{r.version}</b><small>{r.rollout} · {r.severity} · {r.required?"required":"optional"}</small><p style={{whiteSpace:"pre-wrap"}}>{r.changelog||"No changelog"}</p></div><span>{r.status}</span></div>)}{!updates.length&&<div className="lmEmpty">No published update releases.</div>}</div></section></main>;
}
