"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";

const customerName=(i:any)=>i.customer?.display_name||i.customer?.company_name||i.customer?.email||"Customer";
const stateClass=(v:any)=>String(v||"").toLowerCase()==="healthy"?"ready":String(v||"").toLowerCase()==="failed"?"error":"waiting";

export default function OrbitFSUpdateReleaseDeployer(){
 const sb=useMemo(()=>createClient(),[]),[data,setData]=useState<any>(),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[selectedVersion,setSelectedVersion]=useState("");
 async function headers():Promise<Headers>{const {data:{session}}=await sb.auth.getSession();const h=new Headers({"content-type":"application/json"});if(session?.access_token)h.set("Authorization",`Bearer ${session.access_token}`);return h}
 async function load(){setBusy("load");const r=await fetch("/api/admin/orbitfs",{headers:await headers(),cache:"no-store"}),j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return setMsg(j.error||"Could not load release deployment data.");setData(j);setMsg("")}
 useEffect(()=>{void load()},[]);
 const updates=(data?.releases||[]).filter((r:any)=>r.channel==="update").sort((a:any,b:any)=>String(b.publishedAt||b.updatedAt).localeCompare(String(a.publishedAt||a.updatedAt))),latest=data?.latestUpdate,chosen=selectedVersion?(updates.find((r:any)=>r.version===selectedVersion)||latest):latest;
 async function update(installationId:string,version?:string){const target=version||chosen?.version;if(!target)return setMsg("No published update release is available.");if(!confirm(`Deploy OrbitFS update ${target} to this installation?`))return;setBusy(installationId);const r=await fetch("/api/admin/orbitfs/deploy",{method:"POST",headers:await headers(),body:JSON.stringify({installationId,action:"update",version:target})}),j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?`Update ${target} started.`:j.error||"Update failed.");if(r.ok)await load()}
 const installs=(data?.installations||[]).filter((i:any)=>i.release_version),available=!!chosen?.version,counts={available:installs.filter((i:any)=>i.release_version!==chosen?.version).length,current:installs.filter((i:any)=>i.release_version===chosen?.version).length,failed:installs.filter((i:any)=>i.state==="failed").length};
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">ORBITFS · RELEASE MANAGEMENT</div><h1>Update Release Deployer</h1><p>License Master owns release authority. This Store admin tool selects a published Base update and deploys it to an existing customer installation.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink" href="/admin/orbitfs">← My OrbitFS</Link><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div></div>
  <div className="lmGrid2">
   <section className="lmCard"><div className="lmKicker">SELECTED RELEASE</div><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><h2>{chosen?.version||"No published update"}</h2><p>{chosen?.title||"Publish a Base update in License Master first."}</p></div>{chosen&&<span className="state ready">{chosen.status}</span>}</div><div className="lmKV"><div><span>Channel</span><b>{chosen?.channel||"update"}</b></div><div><span>Rollout</span><b>{chosen?.rollout||"—"}</b></div><div><span>Minimum</span><b>{chosen?.minimumVersion||"—"}</b></div><div><span>Required</span><b>{chosen?.required?"Yes":"No"}</b></div></div></section>
   <section className="lmCard"><div className="lmKicker">DEPLOYMENT STATUS</div><h2>Customer fleet</h2><div className="lmKV"><div><span>Update available</span><b>{counts.available}</b></div><div><span>Current</span><b>{counts.current}</b></div><div><span>Failed</span><b>{counts.failed}</b></div><div><span>Release channel</span><b>{data?.settings?.release_channel||"latest"}</b></div></div><p className="muted" style={{marginTop:14}}>Updates reuse the customer's existing Vercel project and Supabase database. No new customer database is created for an update.</p></section>
  </div>
  <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">RELEASE SELECTOR</div><h2>Published Base updates</h2><p>Pick the exact release when a customer needs a specific update or rollback preparation.</p></div></header>{updates.length?<div className="lmReleaseList">{updates.map((r:any)=><button key={r.releaseId} type="button" className="lmRelease" onClick={()=>setSelectedVersion(r.version)} style={{textAlign:"left",width:"100%",border:selectedVersion===r.version?"1px solid currentColor":undefined}}><div><b>{r.version}</b><small>{r.rollout} · {r.severity} · {r.required?"required":"optional"}</small><p style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.description||"No changelog"}</p></div><span>{selectedVersion===r.version?"SELECTED":r.status}</span></button>)}</div>:<div className="lmEmpty">No published update releases.</div>}</section>
  <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">CUSTOMER INSTALLATIONS</div><h2>Deploy selected update</h2><p>Deployment is explicit per installation. The customer database, project and installation identity are retained.</p></div></header>{installs.length?<div className="lmReleaseList">{installs.map((i:any)=>{const newer=available&&i.release_version!==chosen.version;return <div className="lmRelease" key={i.id}><div><b>{customerName(i)}</b><small>{i.installation_id||i.id} · installed {i.release_version}</small><p>{i.vercel_project_name||"Vercel project"} · {i.health_status||"health unknown"}</p></div><span className={`state ${stateClass(i.health_status)}`}>{newer?"UPDATE AVAILABLE":i.release_version===chosen?.version?"CURRENT":"INSTALLED"}</span><div className="actions"><button className="primary" disabled={!!busy||!newer||!available} onClick={()=>void update(i.id,chosen.version)}>{busy===i.id?"Updating…":newer?`Deploy ${chosen.version}`:"Current"}</button></div></div>})}</div>:<div className="lmEmpty">No deployed OrbitFS installations are currently available.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 </main>;
}
