"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";
import "../licensing/licensing.css";

export default function AdminReleaseManager(){
 const sb=useMemo(()=>createClient(),[]),[releases,setReleases]=useState<any[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[draft,setDraft]=useState({version:"",changelog:""});
 async function request(path:string,method="GET",body?:any){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired.");const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(path)}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`License Master returned ${r.status}`);return j}
 async function load(){setLoading(true);try{const j=await request("/api/v1/releases");setReleases((j.releases||[]).filter((r:any)=>String(r.component||"")==="orbitfs_base"&&String(r.channel||"")==="update").sort((a:any,b:any)=>String(b.published_at||b.publishedAt||b.updated_at||b.updatedAt).localeCompare(String(a.published_at||a.publishedAt||a.updated_at||a.updatedAt))));setMsg("")}catch(e:any){setMsg(e.message||"Could not reach License Master releases.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function action(id:string,op:string){if(!confirm(`${op} release ${id}?`))return;setBusy(id+op);try{await request(`/api/v1/releases/${encodeURIComponent(id)}/${op}`,"POST",{});setMsg(`Release ${op} completed.`);await load()}catch(e:any){setMsg(e.message||`Release ${op} failed.`)}finally{setBusy("")}}
 async function createDraft(){if(!draft.version||!draft.changelog)return setMsg("Version and changelog are required.");setBusy("create");try{await request("/api/v1/releases","POST",{component:"orbitfs_base",version:draft.version,channel:"update",title:`OrbitFS Base Update ${draft.version}`,description:"OrbitFS Base update generated for the V1-vercel-base release-updates branch.",changelog:draft.changelog,required:false,rollout:"internal",manifest:{sourceBranch:"release-updates",licenseComponent:"orbitfs_base",packageFormat:"orbitfs-panel-release-v1"}});setMsg("Update release draft created in License Master.");setDraft({version:"",changelog:""});await load()}catch(e:any){setMsg(e.message||"Could not create update release draft.")}finally{setBusy("")}}
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">ORBITFS · RELEASES</div><h1>Releases</h1><p>Authoritative Base updates come from the <b>release-updates</b> branch of V1-vercel-base and are stored and published by License Master.</p></div><div className="lmHeroActions"><Link href="/admin/orbitfs">← My OrbitFS</Link><Link href="/admin/orbitfs/base-deploy">Base Deployment</Link><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div></div>
  <section className="lmCard"><header><div><div className="lmKicker">SOURCE</div><h2>OrbitFS Base Updates</h2><p>Source branch: <b>V1-vercel-base / release-updates</b> · License Master channel: <b>update</b> · component: <b>orbitfs_base</b></p></div></header>
   <div className="lmGrid2"><div className="lmCard"><div className="lmKicker">CREATE UPDATE DRAFT</div><div className="lmKV"><label>Version<input value={draft.version} onChange={e=>setDraft({...draft,version:e.target.value})} placeholder="2.0.1"/></label><label>Changelog<textarea rows={8} value={draft.changelog} onChange={e=>setDraft({...draft,changelog:e.target.value})} placeholder="Added…\nFixed…\nChanged…"/></label></div><button className="primary" disabled={busy==="create"} onClick={()=>void createDraft()}>{busy==="create"?"Creating…":"Create update draft"}</button></div>
   <div className="lmCard"><div className="lmKicker">PIPELINE</div><div className="lmRuntimeList"><div><b>1 · V1-vercel-base</b><span>release-updates branch</span></div><div><b>2 · License Master</b><span>Draft → validate → publish</span></div><div><b>3 · Billing Store</b><span>Reads the published Master release</span></div><div><b>4 · Customer deployment</b><span>Existing Base installation is updated</span></div></div></div></div>
  </section>
  <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">LICENSE MASTER CATALOGUE</div><h2>Published and candidate Base updates</h2></div></header>{loading?<div className="lmLoading">Loading License Master releases…</div>:releases.length?<div className="lmReleaseList">{releases.map((r:any)=><div className="lmRelease" key={r.id}><div><b>{r.version||r.id}</b><small>orbitfs_base · update · {r.status||"draft"}</small><p style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.release_notes||r.description||"No changelog"}</p></div><div className="actions"><button disabled={!!busy||r.status!=="draft"} onClick={()=>void action(r.id,"validate")}>Validate</button><button className="primary" disabled={!!busy||r.status!=="validated"} onClick={()=>void action(r.id,"publish")}>Publish</button><button disabled={!!busy||!['published','validated'].includes(r.status)} onClick={()=>void action(r.id,"pause")}>Pause</button><button className="danger" disabled={!!busy||r.status==='withdrawn'} onClick={()=>void action(r.id,"withdraw")}>Withdraw</button></div></div>)}</div>:<div className="lmEmpty">No Base update releases are currently registered in License Master.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 </main>
}
