"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

const pretty=(v:any)=>String(v||"—").replaceAll("_"," ");
const customerName=(i:any)=>i.customer?.display_name||i.customer?.company_name||i.customer?.email||i.auth_user_id||"Customer";

export default function OrbitFSBaseDeploy(){
 const sb=useMemo(()=>createClient(),[]),[data,setData]=useState<any>(),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function headers():Promise<Record<string,string>>{const {data:{session}}=await sb.auth.getSession();const h:Record<string,string>={};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;return h}
 async function load(){setBusy("load");const r=await fetch("/api/admin/orbitfs",{headers:await headers(),cache:"no-store"}),j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return setMsg(j.error||"Could not load OrbitFS control data.");setData(j);setMsg("")}
 useEffect(()=>{void load()},[]);
 async function deploy(installationId:string,action:"deploy"|"redeploy"){if(!confirm(`${action==='deploy'?'Deploy':'Redeploy'} OrbitFS Base for this installation?`))return;setBusy(`${action}:${installationId}`);const r=await fetch("/api/admin/orbitfs/deploy",{method:"POST",headers:{...await headers(),"content-type":"application/json"},body:JSON.stringify({installationId,action})}),j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?`OrbitFS ${action} started.`:j.error||`${action} failed.`);if(r.ok)await load()}
 const installs=(data?.installations||[]),base=data?.latestBase;
 return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">MY ORBITFS · BASE DEPLOY SYSTEM</div><h1>Base Deploy System</h1><p>Central administrator control for deploying and redeploying the OrbitFS Base Panel into customer Vercel accounts.</p></div><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div>
 <div className="lmGrid2"><section className="lmCard"><header><div><div className="lmKicker">CURRENT BASE</div><h2>{base?.version||"No published Base release"}</h2><p>{base?.title||"Publish a Base release before deployment."}</p></div><span>{base?.status||"—"}</span></header><div className="lmKV"><div><span>Channel</span><b>{base?.channel||"base"}</b></div><div><span>Schema</span><b>{base?.schemaVersion||"—"}</b></div><div><span>Rollout</span><b>{base?.rollout||"—"}</b></div><div><span>Published</span><b>{base?.publishedAt?new Date(base.publishedAt).toLocaleString():"—"}</b></div></div></section><section className="lmCard"><header><div><div className="lmKicker">DEPLOYMENT MODEL</div><h2>Base first</h2></div></header><div className="lmRuntimeList"><div><b>1 · Installation</b><span>Customer installation identity and licence binding.</span></div><div><b>2 · Database</b><span>Customer Supabase remains separate from Store infrastructure.</span></div><div><b>3 · Panel</b><span>Deploy the private Base release into the customer's Vercel account.</span></div><div><b>4 · Ready</b><span>Record the deployed version and health state for updates.</span></div></div></section></div>
 <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">CUSTOMER INSTALLATIONS</div><h2>Base deployment queue</h2><p>Deploy or redeploy existing OrbitFS installations without touching the customer's database.</p></div></header>{installs.length?<div className="lmReleaseList">{installs.map((i:any)=>{const deployed=!!i.release_version;const action=deployed?"redeploy":"deploy";return <div className="lmRelease" key={i.id}><div><b>{customerName(i)}</b><small>{i.installation_id||i.id} · {pretty(i.state)} · {i.release_version?`Base ${i.release_version}`:"Not deployed"}</small><p>{i.vercel_project_name||"No Vercel project"}{i.vercel_project_url?` · ${i.vercel_project_url}`:""}</p></div><span>{i.health_status||"unknown"}</span><div className="actions"><button className="primary" disabled={!!busy||!base} onClick={()=>void deploy(i.id,action)}>{busy===`${action}:${i.id}`?"Working…":action==='deploy'?"Deploy Base":"Redeploy"}</button></div></div>})}</div>:<div className="lmEmpty">No OrbitFS installations found.</div>}{msg&&<p className="small" style={{marginTop:12}}>{msg}</p>}</section></main>;
}
