"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import "./licensing.css";

type View="overview"|"licenses"|"products"|"installations"|"releases"|"deployments"|"settings";
const tabs:[View,string,string][]=[["overview","Overview","Control plane status and authority"],["licenses","Licences","Licence records and controls"],["products","Products","Canonical licensed components"],["installations","Installations","Runtime identities and limits"],["releases","Releases","Release eligibility and channels"],["deployments","Deployments","Deployment/update state"],["settings","Settings","Authority configuration"]];

function Stat({label,value,detail}:{label:string;value:any;detail?:string}){return <div className="lmStat"><span>{label}</span><strong>{String(value??"—")}</strong>{detail&&<small>{detail}</small>}</div>}
function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`lmBadge ${tone}`}>{children}</span>}
function prettyStatus(v:any){const s=String(v??"unknown");if(/active|healthy|published|enabled|online|ready/i.test(s))return "good";if(/suspend|pending|paused|warning|draft/i.test(s))return "warn";if(/terminated|blocked|failed|error|disabled/i.test(s))return "bad";return "neutral"}

export default function LicensingAdmin(){
 const [view,setView]=useState<View>("overview");const [data,setData]=useState<Record<string,any>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const sb=useMemo(()=>createClient(),[]);
 const load=async()=>{setLoading(true);setError("");try{const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Your admin session has expired.");const paths:any={licenses:"/api/v1/licenses",products:"/api/v1/products",installations:"/api/v1/installations",releases:"/api/v1/releases",deployments:"/api/v1/deployments",settings:"/api/v1/settings",revision:"/api/v1/license/revision"};const entries=await Promise.all(Object.entries(paths).map(async([key,path])=>{const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(path)}`,{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(String(d.error||`License Master returned ${r.status}`));return [key,d]}));setData(Object.fromEntries(entries));}catch(e){setError(e instanceof Error?e.message:"Unable to load License Master");}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const licenses=Array.isArray(data.licenses?.licenses)?data.licenses.licenses:[];const products=Array.isArray(data.products?.products)?data.products.products:[];const installations=Array.isArray(data.installations?.installations)?data.installations.installations:[];const releases=Array.isArray(data.releases?.releases)?data.releases.releases:[];const deployments=Array.isArray(data.deployments?.deployments)?data.deployments.deployments:[];const revision=data.revision||{};
 const current= tabs.find(x=>x[0]===view)!;
 return <div className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">License Master · Billing projection</div><h1>{current[1]}</h1><p>{current[2]}</p></div><div className="lmHeroActions"><Badge tone="good">Authority: {revision.authority||"master"}</Badge><span className="lmSource">incendiarynetworks.cc</span><button onClick={load}>Refresh</button></div></div>
  <div className="lmLayout"><aside className="lmNav"><div className="lmNavTitle">LICENSING</div>{tabs.map(([id,label,desc])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><b>{label}</b><small>{desc}</small></button>)}<div className="lmNavFoot"><Link href="/admin">← Billing Admin</Link><span>Live authority projection</span></div></aside>
  <main className="lmContent">{loading&&<div className="lmCard lmLoading">Loading License Master…</div>}{!loading&&error&&<div className="lmCard lmError"><strong>License Master unavailable</strong><p>{error}</p><small>Billing remains separate from licensing authority; this page does not create substitute licence state.</small></div>}{!loading&&!error&&<>
   {view==="overview"&&<><div className="lmStats"><Stat label="Licences" value={licenses.length}/><Stat label="Products" value={products.length}/><Stat label="Installations" value={installations.length}/><Stat label="Releases" value={releases.length}/></div><div className="lmGrid2"><section className="lmCard"><header><div><div className="lmKicker">AUTHORITY</div><h2>License Master connection</h2></div><Badge tone="good">Connected</Badge></header><div className="lmKV"><div><span>Service</span><b>{revision.service||"OrbitFS License Master"}</b></div><div><span>Version</span><b>{revision.version||"2.0.0"}</b></div><div><span>Authority</span><b>{revision.authority||"master"}</b></div><div><span>Endpoint</span><b>https://incendiarynetworks.cc/api</b></div></div></section><section className="lmCard"><header><div><div className="lmKicker">COMPONENT MODEL</div><h2>Canonical runtimes</h2></div></header><div className="lmRuntimeList">{["orbitfs_base","orbitfs_mcp","orbitfs_apex","orbitfs_studio"].map((x,i)=><div key={x}><span>{x}</span><Badge tone="neutral">{i===0?"panel":"engine"}</Badge></div>)}</div></section></div><section className="lmCard"><header><div><div className="lmKicker">RECENT STATE</div><h2>Latest licences</h2></div><button onClick={()=>setView("licenses")}>View all</button></header><div className="lmTableWrap"><table><thead><tr><th>Licence</th><th>Status</th><th>Customer</th><th>Created</th></tr></thead><tbody>{licenses.slice(0,8).map((x:any)=><tr key={x.id}><td><b>{x.id||x.license_id||"—"}</b><small>{x.license_key_last4?`••••${x.license_key_last4}`:"Key protected"}</small></td><td><Badge tone={prettyStatus(x.status)}>{x.status||"unknown"}</Badge></td><td>{x.customer_ref||x.auth_user_id||"—"}</td><td>{x.created_at?new Date(x.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table>{!licenses.length&&<div className="lmEmpty">No licence records returned.</div>}</div></section></>}
   {view==="licenses"&&<section className="lmCard"><header><div><div className="lmKicker">LICENSE MASTER</div><h2>Licence records</h2><p>Read from License Master. Billing does not maintain a second licensing authority.</p></div></header><div className="lmTableWrap"><table><thead><tr><th>ID</th><th>Status</th><th>Customer</th><th>Installation</th><th>Created</th></tr></thead><tbody>{licenses.map((x:any)=><tr key={x.id}><td><code>{x.id||"—"}</code><small>{x.license_key_last4?`Key ••••${x.license_key_last4}`:"Key protected"}</small></td><td><Badge tone={prettyStatus(x.status)}>{x.status||"unknown"}</Badge></td><td>{x.customer_ref||x.auth_user_id||"—"}</td><td>{x.installation_id||"—"}</td><td>{x.created_at?new Date(x.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></section>}
   {view==="products"&&<div className="lmProductGrid">{products.map((p:any)=><section className="lmCard" key={p.id||p.code}><header><div className="lmProductIcon">{String(p.code||p.slug||"OF").slice(-2).toUpperCase()}</div><div><h2>{p.name||p.code||"Product"}</h2><p>{p.code||p.slug}</p></div><Badge tone={p.active===false?"bad":"good"}>{p.active===false?"Disabled":"Active"}</Badge></header><div className="lmKV"><div><span>Runtime</span><b>{p.runtime||p.productType||"—"}</b></div><div><span>Engine required</span><b>{p.requiresEngine==null?"—":p.requiresEngine?"Yes":"No"}</b></div><div><span>Installations</span><b>{p.maxInstallations??"—"}</b></div><div><span>Release channel</span><b>{p.releaseChannel||p.release_channel||"stable"}</b></div></div></section>)}{!products.length&&<div className="lmCard lmEmpty">No products returned.</div>}</div>}
   {view==="installations"&&<section className="lmCard"><header><div><div className="lmKicker">RUNTIME IDENTITY</div><h2>Installations</h2></div></header><div className="lmTableWrap"><table><thead><tr><th>Installation</th><th>Licence</th><th>Product</th><th>Status</th><th>Last seen</th></tr></thead><tbody>{installations.map((x:any)=><tr key={x.id}><td><code>{x.id||"—"}</code></td><td>{x.license_id||x.binding_id||"—"}</td><td>{x.product_code||x.component||"—"}</td><td><Badge tone={prettyStatus(x.status)}>{x.status||"unknown"}</Badge></td><td>{x.last_seen_at?new Date(x.last_seen_at).toLocaleString():x.updated_at?new Date(x.updated_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></section>}
   {view==="releases"&&<section className="lmCard"><header><div><div className="lmKicker">RELEASE CONTROL</div><h2>Releases</h2><p>Release eligibility stays authoritative in License Master.</p></div></header><div className="lmReleaseList">{releases.map((x:any)=><div className="lmRelease" key={x.id}><div><b>{x.name||x.version||x.id}</b><small>{x.product_code||x.component||"OrbitFS"} · {x.channel||x.release_channel||"stable"}</small></div><Badge tone={prettyStatus(x.status||x.state)}>{x.status||x.state||"published"}</Badge><span>{x.created_at?new Date(x.created_at).toLocaleDateString():"—"}</span></div>)}{!releases.length&&<div className="lmEmpty">No releases returned.</div>}</div></section>}
   {view==="deployments"&&<section className="lmCard"><header><div><div className="lmKicker">DEPLOYMENT CONTROL</div><h2>Deployments</h2><p>Deployment state is displayed here; execution remains with the release/deployment system.</p></div></header><div className="lmReleaseList">{deployments.map((x:any)=><div className="lmRelease" key={x.id}><div><b>{x.project_name||x.name||x.id}</b><small>{x.installation_id||"No installation"} · {x.provider||"Vercel"}</small></div><Badge tone={prettyStatus(x.status)}>{x.status||"unknown"}</Badge><span>{x.updated_at?new Date(x.updated_at).toLocaleString():"—"}</span></div>)}{!deployments.length&&<div className="lmEmpty">No deployments returned.</div>}</div></section>}
   {view==="settings"&&<div className="lmGrid2"><section className="lmCard"><header><div><div className="lmKicker">AUTHORITY CONFIGURATION</div><h2>Master settings</h2></div></header><pre className="lmJson">{JSON.stringify(data.settings?.settings||data.settings||{},null,2)}</pre></section><section className="lmCard"><header><div><div className="lmKicker">INTEGRATION</div><h2>Billing projection</h2></div></header><div className="lmNotice"><b>Read-through architecture</b><p>This UI is hosted by orbitfsstore.vercel.app, but licensing data comes from the License Master API at incendiarynetworks.cc. The Store does not write License Master tables directly.</p></div><div className="lmKV"><div><span>Configured master</span><b>https://incendiarynetworks.cc</b></div><div><span>API model</span><b>Server-to-server billing token</b></div><div><span>Browser access</span><b>Never receives the master token</b></div></div></section></div>}
  </>}</main></div></div>
}
