"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
export default function OrbitFSReleaseDeployer(){
 const sb=useMemo(()=>createClient(),[]);const [d,setD]=useState<any>(),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 async function load(){const {data:{session}}=await sb.auth.getSession();const r=await fetch("/api/orbitfs/status",{headers:session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{},cache:"no-store"});const j=await r.json().catch(()=>({}));if(r.ok)setD(j);else setMsg(j.error||"Could not load releases.")}
 useEffect(()=>{void load()},[]);const binding=(d?.bindings||[]).find((x:any)=>x.license_product_key==="orbitfs_base"||x.components?.orbitfs_base)||d?.bindings?.[0],install=(d?.installations||[]).find((x:any)=>x.license_binding_id===binding?.id),releases=(d?.releases||[]).filter((x:any)=>!install?.id||!x.installation_id||x.installation_id===install.id),latest=d?.latestUpdate?.version;
 async function deploy(version?:string){if(!install)return setMsg("Start your OrbitFS installation first.");if(!confirm(`Deploy OrbitFS ${version||latest||"latest"}?`))return;setBusy(version||"latest");setMsg("");const {data:{session}}=await sb.auth.getSession();const r=await fetch(`/api/orbitfs/installations/${install.id}/deploy`,{method:"POST",headers:{...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}) ,"Content-Type":"application/json"},body:JSON.stringify({action:install.release_version?"update":"deploy",version:version||latest})});const j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?(j.message||"Deployment started."):(j.error||"Deployment failed."));if(r.ok)await load()}
 if(!d)return <main className="portalOverviewV2"><section className="panel">Loading Release Deployer…</section></main>;
 return <main className="portalOverviewV2"><header className="portalOverviewHero"><div><p className="eyebrow">RELEASE DEPLOYER</p><h1>OrbitFS releases</h1><p className="muted">Review published releases and their changelogs, then deploy an update into your existing Vercel project.</p></div><div style={{display:"flex",gap:8}}><Link className="buttonlink" href="/portal/orbitfs">My OrbitFS</Link><Link className="buttonlink" href="/portal/orbitfs/license">License Controller</Link></div></header><section className="panel"><div className="panelTitle"><div><p className="eyebrow">CURRENT INSTALLATION</p><h2>{install?.vercel_project_name||"OrbitFS Panel"}</h2><p className="muted">Installed {install?.release_version?`v${install.release_version}`:"release not yet deployed"} · {install?.state||"waiting"}</p></div><span className={`state ${install?.state||"waiting"}`}>{install?.health_status||install?.state||"WAITING"}</span></div>{latest&&install?.release_version!==latest&&<div className="listrow"><div><b>Update available: v{latest}</b><span>A published License Master release is newer than your installation.</span></div><button disabled={!!busy||!install} onClick={()=>void deploy(latest)}>{busy===latest?"Starting…":"Deploy update"}</button></div>}</section><div className="portalOverviewGrid">{releases.length?releases.map((r:any)=><article className="panel" key={r.id||r.version}><div className="panelTitle"><div><p className="eyebrow">{r.component||r.product_code||"ORBITFS"} · {r.channel||r.release_channel||"stable"}</p><h2>v{r.version||r.name||"Unknown"}</h2><p className="muted">{r.published_at?new Date(r.published_at).toLocaleString():r.created_at?new Date(r.created_at).toLocaleString():"Published release"}</p></div><span className={`state ${r.status||"ready"}`}>{r.status||"PUBLISHED"}</span></div><div><p className="eyebrow">CHANGELOG</p><div style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.release_notes||r.notes||"No changelog supplied for this release."}</div></div><div style={{display:"flex",gap:8,marginTop:14}}><button disabled={!!busy||!install} onClick={()=>void deploy(r.version)}>{busy===r.version?"Deploying…":install?.release_version===r.version?"Installed":"Deploy this release"}</button></div></article>):<section className="panel"><h2>No published releases</h2><p className="muted">When License Master publishes a release, it will appear here with its changelog and deployment action.</p></section>}</div>{msg&&<section className="panel" style={{marginTop:12}}><p>{msg}</p></section>}</main>;
}
