"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase";
import "../orbitfs.css";

export default function OrbitFSLicenseController(){
 const sb=useMemo(()=>createClient(),[]);const [d,setD]=useState<any>(),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 async function load(){const {data:{session}}=await sb.auth.getSession();const r=await fetch("/api/orbitfs/status",{headers:session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{},cache:"no-store"});const j=await r.json().catch(()=>({}));if(r.ok)setD(j);else setMsg(j.error||"Could not load your licence.")}
 useEffect(()=>{void load()},[]);
 const binding=(d?.bindings||[]).find((x:any)=>x.license_product_key==="orbitfs_base"||x.components?.orbitfs_base)||d?.bindings?.[0];
 const install=(d?.installations||[]).find((x:any)=>x.license_binding_id===binding?.id);
 async function control(action:string){if(!binding?.license_id)return setMsg("No License Master licence ID is available for this account.");const question=action==="rotate"?"Rotate your licence key? Your previous key will no longer be the active key.":action==="unlock"?"Unlock an installation? This only affects installation authorisation in License Master.":"Apply this licence action?";if(!confirm(question))return;setBusy(action);setMsg("");const {data:{session}}=await sb.auth.getSession();if(!session?.access_token){setBusy("");return setMsg("Your session has expired. Please sign in again.")}const r=await fetch("/api/orbitfs/license-control",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({licenseId:binding.license_id,installationId:install?.id||null,action})});const j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?(j.message||`Licence ${action} completed.`):(j.error||`Licence ${action} failed.`));if(r.ok)await load()}
 if(!d)return <main className="portalOverviewV2"><section className="panel">Loading License Controller…</section></main>;
 return <main className="portalOverviewV2"><header className="portalOverviewHero"><div><p className="eyebrow">LICENSE CONTROLLER</p><h1>Your OrbitFS licence</h1><p className="muted">Licence state is read from the OrbitFS License Master at incendiarynetworks.cc. The Store does not create a replacement licence authority.</p></div><Link className="buttonlink" href="/portal/orbitfs">← My OrbitFS</Link></header><div className="portalOverviewGrid"><section className="panel"><div className="panelTitle"><div><p className="eyebrow">LICENCE</p><h2>{binding?.label||binding?.license_product_key||"OrbitFS"}</h2><p className="muted">{binding?.license_id||"No licence ID returned"}</p></div><span className={`state ${binding?.desired_state||"waiting"}`}>{binding?.remote_state||binding?.desired_state||"UNKNOWN"}</span></div><div className="portalOverviewStats"><div className="portalStatCard"><div><small>KEY</small><strong>{binding?.license_key_last4?`••••${binding.license_key_last4}`:"Protected"}</strong><span>Full key is not displayed here.</span></div></div><div className="portalStatCard"><div><small>INSTALLATION</small><strong>{install?.installation_id||"Not registered"}</strong><span>{install?.state||"Waiting"}</span></div></div><div className="portalStatCard"><div><small>EXPIRES</small><strong>{binding?.expires_at?new Date(binding.expires_at).toLocaleDateString():"No expiry"}</strong><span>License Master value</span></div></div></div></section><section className="panel"><div className="panelTitle"><div><p className="eyebrow">PERMITTED ACTIONS</p><h2>Manage licence</h2><p className="muted">Available customer actions are intentionally narrower than administrator enforcement controls.</p></div></div><div className="actions" style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={!!busy||!binding?.license_id} onClick={()=>void control("rotate")}>{busy==="rotate"?"Rotating…":"Rotate key"}</button><button className="secondary" disabled={!!busy||!binding?.license_id} onClick={()=>void control("unlock")}>{busy==="unlock"?"Unlocking…":"Unlock installation"}</button></div>{msg&&<p className="small" style={{marginTop:12}}>{msg}</p>}</section><section className="panel"><p className="eyebrow">AUTHORITY</p><h2>License Master</h2><p className="muted">Activation, suspension, termination and full enforcement remain administrator controls. Customer actions are passed through the Billing Store server to the License Master API.</p><div className="listrow"><b>Authority</b><span>incendiarynetworks.cc</span></div><div className="listrow"><b>Licence ID</b><span>{binding?.license_id||"—"}</span></div></section></div></main>;
}
