"use client";

import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {createClient} from "@/lib/supabase";

export default function AdminCustomerLicenseActions(){
 const path=usePathname();
 const customerId=useMemo(()=>{const m=path.match(/^\/admin\/customers\/([^/]+)/);return m?m[1]:""},[path]);
 const sb=useMemo(()=>createClient(),[]);
 const [bindings,setBindings]=useState<any[]>([]),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function load(){if(!customerId)return;const {data,error}=await sb.from("license_bindings").select("id,license_id,license_product_key,desired_state,remote_state,license_key_last4,expires_at,components,label,archived_at").eq("auth_user_id",customerId).is("archived_at",null).order("created_at",{ascending:false});if(!error)setBindings(data||[])}
 useEffect(()=>{void load()},[customerId]);
 async function control(licenseId:string,action:string){if(!licenseId)return;const text=action==="terminate"?"Terminate this licence? This may require reissue to restore access.":action==="suspend"?"Suspend this licence?":"Apply this licence control?";if(!confirm(text))return;setBusy(`${licenseId}:${action}`);setMsg("");const {data:{session}}=await sb.auth.getSession();if(!session?.access_token){setMsg("Administrator session expired.");setBusy("");return}const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(`/api/v1/license/${encodeURIComponent(licenseId)}/control`)}`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action})});const j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?`Licence ${action} completed.`:(j.error||`Licence ${action} failed.`));if(r.ok)await load()}
 if(!customerId)return null;
 return <section className="panel adminCustomerLicenseActions" style={{marginBottom:14}}><div className="head"><div><p className="eyebrow">LICENSE CONTROLLER</p><h2>Customer licensing</h2><p className="muted">These controls operate on the License Master authority, not a local billing copy.</p></div><a className="buttonlink" href="/admin/licensing">Open License Master</a></div>{bindings.length===0?<p className="muted">No active licence bindings found for this customer.</p>:<div className="listrow" style={{display:"grid",gap:10}}>{bindings.map((b:any)=><div key={b.id} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,alignItems:"center",padding:"10px 0",borderBottom:"1px solid var(--line,#ddd)"}}><div><b>{b.label||b.license_product_key||"Licence"}</b><span style={{display:"block",fontSize:12,opacity:.72}}>{b.license_id||b.id} · {b.license_key_last4?`••••${b.license_key_last4}`:"Key protected"} · {b.remote_state||b.desired_state||"unknown"}</span></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}><button className="secondary" disabled={!!busy} onClick={()=>control(b.license_id,"activate")}>Reactivate</button><button className="secondary" disabled={!!busy} onClick={()=>control(b.license_id,"suspend")}>Suspend</button><button className="secondary" disabled={!!busy} onClick={()=>control(b.license_id,"unlock")}>Unlock installations</button><button className="secondary" disabled={!!busy} onClick={()=>control(b.license_id,"rotate")}>Rotate key</button><button className="danger" disabled={!!busy} onClick={()=>control(b.license_id,"terminate")}>Block / terminate</button></div></div>)}</div>}{msg&&<p className="small" style={{marginTop:10}}>{msg}</p>}</section>
}
